package Reserva;

import Inicial.Registro;
import Objetos.Vuelo;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class ReservaVentana1 extends javax.swing.JFrame {

    DefaultTableModel modeloTablaVuelos;
    Registro r = new Registro();

    public ReservaVentana1() {
        initComponents();

        //Tabla
        String cabeceraVuelos[] = {"Codigo", "Aerolinea", "Ciudad Origen", "Ciudad Destino", "Hora Origen", "Hora Destino"};
        String datos[][] = {};
        modeloTablaVuelos = new DefaultTableModel(datos, cabeceraVuelos);
        tablaVuelos.setModel(modeloTablaVuelos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelOrigen = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        botonBuscarVuelos = new javax.swing.JButton();
        campoOrigen = new javax.swing.JTextField();
        campoDestino = new javax.swing.JTextField();
        labelFechaDePartida = new javax.swing.JLabel();
        labelFechaDeRegreso = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        seleccionFechaOrigen = new com.toedter.calendar.JDateChooser();
        seleccionFechaDestino = new com.toedter.calendar.JDateChooser();
        labelCodigoVuelo = new javax.swing.JLabel();
        campoCodigoVuelo = new javax.swing.JTextField();
        botonBuscarVueloPorCodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TERMINAL AEREA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 11, 185, 34));

        labelOrigen.setText("Origen (Ciudad, Aeropuerto):");
        getContentPane().add(labelOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 121, -1, -1));

        labelDestino.setText("Destino (Ciudad, Aeropuerto):");
        getContentPane().add(labelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        botonBuscarVuelos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonBuscarVuelos.setText("Buscar Vuelos");
        botonBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVuelosActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        getContentPane().add(campoOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 178, -1));
        getContentPane().add(campoDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 174, -1));

        labelFechaDePartida.setText("Fecha de Partida:");
        getContentPane().add(labelFechaDePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        labelFechaDeRegreso.setText("Fecha de Regreso:");
        getContentPane().add(labelFechaDeRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 150, -1, -1));

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVuelosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVuelos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 218, 650, 226));
        getContentPane().add(seleccionFechaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 133, -1));
        getContentPane().add(seleccionFechaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 123, -1));

        labelCodigoVuelo.setText("Codigo Vuelo:");
        getContentPane().add(labelCodigoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 88, -1, -1));
        getContentPane().add(campoCodigoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 85, 128, -1));

        botonBuscarVueloPorCodigo.setText("Buscar Vuelo por Código");
        botonBuscarVueloPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVueloPorCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarVueloPorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 84, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVuelosActionPerformed
        // TODO add your handling code here:
        String aeropuertoOrigen = campoOrigen.getText();
        String aeropuertoDestino = campoDestino.getText();

        try {

            String diaOrigen = Integer.toString(seleccionFechaOrigen.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mesOrigen = Integer.toString(seleccionFechaOrigen.getCalendar().get(Calendar.MONTH) + 1);
            String yearOrigen = Integer.toString(seleccionFechaOrigen.getCalendar().get(Calendar.YEAR));

            String diaDestino = Integer.toString(seleccionFechaDestino.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mesDestino = Integer.toString(seleccionFechaDestino.getCalendar().get(Calendar.MONTH) + 1);
            String yearDestino = Integer.toString(seleccionFechaDestino.getCalendar().get(Calendar.YEAR));

            String fechaOrigen = (diaOrigen + "/" + mesOrigen + "/" + yearOrigen);
            String fechaDestino = (diaDestino + "/" + mesDestino + "/" + yearDestino);

            if (fechaOrigen.equals("") || fechaDestino.equals("") || aeropuertoOrigen.equals("") || aeropuertoDestino.equals("")) {
                JOptionPane.showMessageDialog(null, "Verifique que todos los campos esten completos.");
            } else {
                buscarVueloPorCiudad(aeropuertoOrigen, aeropuertoDestino, fechaOrigen, fechaDestino);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique que todos los campos esten completos.");
        }


    }//GEN-LAST:event_botonBuscarVuelosActionPerformed

    public void buscarVueloPorCiudad(String ciudadOrigen, String ciudadDestino, String fechaOrigen, String fechaDestino) {

        for (Iterator iterator = r.getListadoVuelos().values().iterator(); iterator.hasNext();) {

            Object valorVuelo = iterator.next();

            Vuelo vuelo = (Vuelo) valorVuelo;

            if (r.getListadoVuelos().containsValue(vuelo) == true) {

                if (vuelo.getOrigenTrayecto().getCiudad().equals(ciudadOrigen) && vuelo.getDestinoTrayecto().getCiudad().equals(ciudadDestino) && vuelo.getFechaOrigen().equals(fechaOrigen) && vuelo.getFechaDestino().equals(fechaDestino)) {

                    String codigoVuelo = vuelo.getCodigoVuelo();
                    String aerolinea = vuelo.getAerolinea().getCodigo();

                    String origenTrayecto = vuelo.getOrigenTrayecto().getCiudad();
                    String destinoTrayecto = vuelo.getDestinoTrayecto().getCiudad();
                    /*
                    String numSillasEjecutiva = vuelo.getSillasClaseEjecutiva();
                    String valorEjecutiva = vuelo.getPrecioPantallaEjecutiva();
                    String numSillasEconomica = vuelo.getSillasClaseEconomica();
                    String valorEconomica = vuelo.getPrecioPantallaEconomica();

                    String fechaOrigenTrayecto = vuelo.getHoraOrigen();
                    String fechaDestinoTrayecto = vuelo.getHoraDestino();*/

                    String horaOrigen = vuelo.getHoraOrigen();
                    String horaDestino = vuelo.getHoraDestino();

                    String vueloEnPantalla[] = {codigoVuelo, aerolinea, origenTrayecto, destinoTrayecto, horaOrigen, horaDestino};
                    modeloTablaVuelos.addRow(vueloEnPantalla);

                }

            }

        }
    }

    private void botonBuscarVueloPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVueloPorCodigoActionPerformed
        // TODO add your handling code here:
        String codigoVuelo = campoCodigoVuelo.getText();
        buscarVueloPorCodigo(codigoVuelo);

    }//GEN-LAST:event_botonBuscarVueloPorCodigoActionPerformed

    private void tablaVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVuelosMouseClicked
        // TODO add your handling code here:
        int fila = tablaVuelos.rowAtPoint(evt.getPoint());
        if (fila > -1) {

            String codigoVuelo = tablaVuelos.getValueAt(fila, 0).toString();
            
            Vuelo v = r.getListadoVuelos().get(codigoVuelo);
            
            ReservaVentana2 ventana2 = new ReservaVentana2(v);
            ventana2.setVisible(Boolean.TRUE);
            ventana2.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

            ventana2.getCampoCodigoVuelo().setText(codigoVuelo);

        }
    }//GEN-LAST:event_tablaVuelosMouseClicked

    public void buscarVueloPorCodigo(String codigoVuelo) {
        int tamaño = r.getListadoVuelos().size();
        System.out.println("Numero de vuelos registrados: " + tamaño);
        if (r.getListadoVuelos().containsKey(codigoVuelo)) {
            Vuelo vuelo = r.getListadoVuelos().get(codigoVuelo);
            //JOptionPane.showMessageDialog(null, vuelo.toString());
            
            String codigo = vuelo.getCodigoVuelo();
            String codigoAerolinea = vuelo.getAerolinea().getCodigo();
            String ciudadOrigen = vuelo.getOrigenTrayecto().getCiudad();
            String ciudadDestino = vuelo.getDestinoTrayecto().getCiudad();
            String horaOrigen = vuelo.getHoraOrigen();
            String horaDestino = vuelo.getHoraDestino();
            
             String vueloEnPantalla[] = {codigoVuelo, codigoAerolinea, ciudadOrigen, ciudadDestino, horaOrigen, horaDestino};
                    modeloTablaVuelos.addRow(vueloEnPantalla);
            
            
            
            //seleccionFechaDestino.set
        } else {
            JOptionPane.showMessageDialog(null, "El vuelo con el codigo que ingreso no existe en el sistema");
        }
    }

    /*public void buscarVueloPorCodigo2(String codigoVuelo) {
        int tamaño = r.getListadoVuelos().size();
        System.out.println("Numero de vuelos registrados: " + tamaño);
        if (r.getListadoVuelos().containsKey(codigoVuelo)) {
            Vuelo vuelo = r.getListadoVuelos().get(codigoVuelo);

        } else {
            JOptionPane.showMessageDialog(null, "El vuelo con el codigo que ingreso no existe en el sistema");
        }
    }*/

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaVentana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaVentana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaVentana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaVentana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReservaVentana1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarVueloPorCodigo;
    private javax.swing.JButton botonBuscarVuelos;
    private javax.swing.JTextField campoCodigoVuelo;
    private javax.swing.JTextField campoDestino;
    private javax.swing.JTextField campoOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodigoVuelo;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelFechaDePartida;
    private javax.swing.JLabel labelFechaDeRegreso;
    private javax.swing.JLabel labelOrigen;
    private com.toedter.calendar.JDateChooser seleccionFechaDestino;
    private com.toedter.calendar.JDateChooser seleccionFechaOrigen;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables
}
