package Reserva;

import Inicial.Registro;
import Objetos.Pasajero;
import Objetos.Reserva;
import Objetos.ReservaEconomico;
import Objetos.ReservaEjecutivo;
import Objetos.Vuelo;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class ReservaVentana2 extends javax.swing.JFrame {

    private Registro r = new Registro();

    private Vuelo vueloReserva;

    private int precioEconomico;
    private int precioEjecutivo;

    private File archivoReservas = new File("reservas.re");
    private HashMap<Vuelo, Reserva> listadoReservas = new HashMap<>();

    private Reserva listadoReservasEjecutivo[][] = new ReservaEjecutivo[2][4];
    private Reserva listadoReservaEconomico[][] = new ReservaEjecutivo[8][6];

    public ReservaVentana2(Vuelo v) {
        vueloReserva = v;
        precioEconomico = vueloReserva.getPrecioClaseEconomica();
        precioEjecutivo = vueloReserva.getPrecioClaseEjecutiva();
        initComponents();
        leerReservas();
        cargarReservas(v.getCodigoVuelo());
        campoNombreAerolinea.setText(vueloReserva.getAerolinea().getCodigo());
        campoPrecioEjecutivo.setText(vueloReserva.getPrecioPantallaEjecutiva());
        campoPrecioEconomico.setText(vueloReserva.getPrecioPantallaEconomica());
        campoAeropuertoOrigen.setText(vueloReserva.getOrigenTrayecto().getNombre());
        campoAeropuertoDestino.setText(vueloReserva.getDestinoTrayecto().getNombre());
        ImageIcon logo = new ImageIcon("src/Reserva/Puestos.jpg");
        Icon icono = new ImageIcon(logo.getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_DEFAULT));
        labelImagen.setIcon(icono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPuestoSeleccionado = new javax.swing.JLabel();
        campoPuestoSeleccionado = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        labelModoPago = new javax.swing.JLabel();
        comboTipoPago = new javax.swing.JComboBox<>();
        botonGenerarReserva = new javax.swing.JButton();
        campoCodigoVuelo = new javax.swing.JTextField();
        panelImagenAvion = new javax.swing.JPanel();
        botonB30 = new javax.swing.JButton();
        botonB24 = new javax.swing.JButton();
        botonB10 = new javax.swing.JButton();
        botonB11 = new javax.swing.JButton();
        botonB12 = new javax.swing.JButton();
        botonB47 = new javax.swing.JButton();
        botonB46 = new javax.swing.JButton();
        botonB48 = new javax.swing.JButton();
        botonB34 = new javax.swing.JButton();
        botonB35 = new javax.swing.JButton();
        botonB36 = new javax.swing.JButton();
        botonB40 = new javax.swing.JButton();
        botonB28 = new javax.swing.JButton();
        botonB22 = new javax.swing.JButton();
        botonB23 = new javax.swing.JButton();
        botonB41 = new javax.swing.JButton();
        botonB42 = new javax.swing.JButton();
        botonB29 = new javax.swing.JButton();
        botonB16 = new javax.swing.JButton();
        botonB17 = new javax.swing.JButton();
        botonB18 = new javax.swing.JButton();
        botonB5 = new javax.swing.JButton();
        botonB6 = new javax.swing.JButton();
        botonB4 = new javax.swing.JButton();
        botonE7 = new javax.swing.JButton();
        botonE8 = new javax.swing.JButton();
        botonE4 = new javax.swing.JButton();
        botonE3 = new javax.swing.JButton();
        botonA44 = new javax.swing.JButton();
        botonA43 = new javax.swing.JButton();
        botonA45 = new javax.swing.JButton();
        botonA31 = new javax.swing.JButton();
        botonA32 = new javax.swing.JButton();
        botonA37 = new javax.swing.JButton();
        botonA33 = new javax.swing.JButton();
        botonA25 = new javax.swing.JButton();
        botonA19 = new javax.swing.JButton();
        botonA20 = new javax.swing.JButton();
        botonA38 = new javax.swing.JButton();
        botonA39 = new javax.swing.JButton();
        botonA26 = new javax.swing.JButton();
        botonA13 = new javax.swing.JButton();
        botonA14 = new javax.swing.JButton();
        botonA15 = new javax.swing.JButton();
        botonA2 = new javax.swing.JButton();
        botonA3 = new javax.swing.JButton();
        botonA1 = new javax.swing.JButton();
        botonA27 = new javax.swing.JButton();
        botonE5 = new javax.swing.JButton();
        botonE6 = new javax.swing.JButton();
        botonE2 = new javax.swing.JButton();
        botonA21 = new javax.swing.JButton();
        botonE1 = new javax.swing.JButton();
        botonA7 = new javax.swing.JButton();
        botonA8 = new javax.swing.JButton();
        botonA9 = new javax.swing.JButton();
        labelImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNombreAerolinea = new javax.swing.JTextField();
        campoPrecioEjecutivo = new javax.swing.JTextField();
        campoPrecioEconomico = new javax.swing.JTextField();
        campoAeropuertoOrigen = new javax.swing.JTextField();
        campoAeropuertoDestino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Reserva"));

        labelPuestoSeleccionado.setText("Puesto Seleccionado:");

        campoPuestoSeleccionado.setEditable(false);

        labelNombre.setText("Nombre:");

        labelApellido.setText("Apellido:");

        jLabel1.setText("Cedula:");

        labelModoPago.setText("Tipo de Pago:");

        comboTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de Crédito", "Efectivo" }));

        botonGenerarReserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGenerarReserva.setText("Generar Reserva");
        botonGenerarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPuestoSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPuestoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelApellido)
                        .addGap(18, 18, 18)
                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelModoPago)
                                .addGap(18, 18, 18)
                                .addComponent(comboTipoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(botonGenerarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPuestoSeleccionado)
                    .addComponent(campoPuestoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelModoPago)
                            .addComponent(comboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGenerarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        campoCodigoVuelo.setEditable(false);
        campoCodigoVuelo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        panelImagenAvion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelImagenAvion.setLayout(null);

        botonB30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB30ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB30);
        botonB30.setBounds(130, 200, 30, 19);

        botonB24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB24ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB24);
        botonB24.setBounds(160, 200, 30, 19);

        botonB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB10ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB10);
        botonB10.setBounds(220, 160, 30, 19);

        botonB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB11ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB11);
        botonB11.setBounds(220, 180, 30, 19);

        botonB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB12ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB12);
        botonB12.setBounds(220, 200, 30, 19);

        botonB47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB47ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB47);
        botonB47.setBounds(30, 180, 30, 19);

        botonB46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB46ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB46);
        botonB46.setBounds(30, 160, 30, 19);

        botonB48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB48ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB48);
        botonB48.setBounds(30, 200, 30, 19);

        botonB34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB34ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB34);
        botonB34.setBounds(100, 160, 30, 19);

        botonB35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB35ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB35);
        botonB35.setBounds(100, 180, 30, 19);

        botonB36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB36ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB36);
        botonB36.setBounds(100, 200, 30, 19);

        botonB40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB40ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB40);
        botonB40.setBounds(62, 160, 30, 19);

        botonB28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB28ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB28);
        botonB28.setBounds(130, 160, 30, 19);

        botonB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB22ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB22);
        botonB22.setBounds(160, 160, 30, 19);

        botonB23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB23ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB23);
        botonB23.setBounds(160, 180, 30, 19);

        botonB41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB41ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB41);
        botonB41.setBounds(62, 180, 30, 19);

        botonB42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB42ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB42);
        botonB42.setBounds(62, 200, 30, 19);

        botonB29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB29ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB29);
        botonB29.setBounds(130, 180, 30, 19);

        botonB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB16ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB16);
        botonB16.setBounds(190, 160, 30, 19);

        botonB17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB17ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB17);
        botonB17.setBounds(190, 180, 30, 19);

        botonB18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB18ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB18);
        botonB18.setBounds(190, 200, 30, 19);

        botonB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB5ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB5);
        botonB5.setBounds(260, 180, 30, 19);

        botonB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB6ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB6);
        botonB6.setBounds(260, 200, 30, 19);

        botonB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB4ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonB4);
        botonB4.setBounds(260, 160, 30, 19);

        botonE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE7ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE7);
        botonE7.setBounds(320, 170, 33, 21);

        botonE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE8ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE8);
        botonE8.setBounds(320, 190, 33, 23);

        botonE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE4ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE4);
        botonE4.setBounds(370, 190, 33, 21);

        botonE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE3ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE3);
        botonE3.setBounds(370, 170, 33, 21);

        botonA44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA44ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA44);
        botonA44.setBounds(30, 110, 30, 19);

        botonA43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA43ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA43);
        botonA43.setBounds(30, 90, 30, 19);

        botonA45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA45ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA45);
        botonA45.setBounds(30, 130, 33, 19);

        botonA31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA31ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA31);
        botonA31.setBounds(100, 90, 30, 19);

        botonA32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA32ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA32);
        botonA32.setBounds(100, 110, 30, 19);

        botonA37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA37ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA37);
        botonA37.setBounds(60, 90, 30, 19);

        botonA33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA33ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA33);
        botonA33.setBounds(100, 130, 30, 19);

        botonA25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA25ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA25);
        botonA25.setBounds(130, 90, 30, 19);

        botonA19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA19ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA19);
        botonA19.setBounds(162, 90, 30, 19);

        botonA20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA20ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA20);
        botonA20.setBounds(162, 110, 30, 19);

        botonA38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA38ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA38);
        botonA38.setBounds(60, 110, 30, 19);

        botonA39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA39ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA39);
        botonA39.setBounds(60, 130, 30, 19);

        botonA26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA26ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA26);
        botonA26.setBounds(130, 110, 30, 19);

        botonA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA13ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA13);
        botonA13.setBounds(190, 90, 30, 19);

        botonA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA14ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA14);
        botonA14.setBounds(190, 110, 30, 19);

        botonA15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA15ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA15);
        botonA15.setBounds(190, 130, 30, 19);

        botonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA2ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA2);
        botonA2.setBounds(260, 110, 30, 19);

        botonA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA3ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA3);
        botonA3.setBounds(260, 130, 30, 19);

        botonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA1ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA1);
        botonA1.setBounds(260, 90, 30, 19);

        botonA27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA27ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA27);
        botonA27.setBounds(130, 130, 30, 19);

        botonE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE5ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE5);
        botonE5.setBounds(320, 100, 33, 21);

        botonE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE6ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE6);
        botonE6.setBounds(320, 120, 33, 23);

        botonE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE2ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE2);
        botonE2.setBounds(370, 120, 33, 21);

        botonA21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA21ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA21);
        botonA21.setBounds(162, 130, 30, 19);

        botonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonE1ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonE1);
        botonE1.setBounds(370, 100, 33, 21);

        botonA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA7ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA7);
        botonA7.setBounds(220, 90, 30, 19);

        botonA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA8ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA8);
        botonA8.setBounds(220, 110, 30, 19);

        botonA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA9ActionPerformed(evt);
            }
        });
        panelImagenAvion.add(botonA9);
        botonA9.setBounds(220, 130, 30, 19);
        panelImagenAvion.add(labelImagen);
        labelImagen.setBounds(20, 10, 750, 280);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Vuelo"));

        jLabel2.setText("Nombre Aerolinea:");

        jLabel3.setText("Precio Ejecutivo:");

        jLabel4.setText("Precio Economico:");

        jLabel5.setText("Aeropuerto Origen:");

        jLabel6.setText("Aeropuerto Destino:");

        campoNombreAerolinea.setEditable(false);

        campoPrecioEjecutivo.setEditable(false);

        campoPrecioEconomico.setEditable(false);

        campoAeropuertoOrigen.setEditable(false);

        campoAeropuertoDestino.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNombreAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPrecioEjecutivo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPrecioEconomico))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoAeropuertoOrigen))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoAeropuertoDestino)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoPrecioEjecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoPrecioEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoAeropuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoAeropuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImagenAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImagenAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE7ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E7");
    }//GEN-LAST:event_botonE7ActionPerformed

    private void botonE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE4ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E4");
    }//GEN-LAST:event_botonE4ActionPerformed

    private void botonE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE3ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E3");
    }//GEN-LAST:event_botonE3ActionPerformed

    private void botonE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE5ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E5");
    }//GEN-LAST:event_botonE5ActionPerformed

    private void botonE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE2ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E2");
    }//GEN-LAST:event_botonE2ActionPerformed

    private void botonE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE1ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E1");
    }//GEN-LAST:event_botonE1ActionPerformed

    private void botonE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE6ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E6");
    }//GEN-LAST:event_botonE6ActionPerformed

    private void botonE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonE8ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("E8");
    }//GEN-LAST:event_botonE8ActionPerformed

    private void botonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA1ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A1");
    }//GEN-LAST:event_botonA1ActionPerformed

    private void botonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA2ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A2");
    }//GEN-LAST:event_botonA2ActionPerformed

    private void botonA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA3ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A3");
    }//GEN-LAST:event_botonA3ActionPerformed

    private void botonB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB4ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B4");
    }//GEN-LAST:event_botonB4ActionPerformed

    private void botonB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB5ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B5");
    }//GEN-LAST:event_botonB5ActionPerformed

    private void botonB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB6ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B6");
    }//GEN-LAST:event_botonB6ActionPerformed

    private void botonA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA7ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A7");
    }//GEN-LAST:event_botonA7ActionPerformed

    private void botonA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA8ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A8");
    }//GEN-LAST:event_botonA8ActionPerformed

    private void botonA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA9ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A9");
    }//GEN-LAST:event_botonA9ActionPerformed

    private void botonB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB10ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B10");
    }//GEN-LAST:event_botonB10ActionPerformed

    private void botonB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB11ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B11");
    }//GEN-LAST:event_botonB11ActionPerformed

    private void botonB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB12ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B12");
    }//GEN-LAST:event_botonB12ActionPerformed

    private void botonA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA13ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A13");
    }//GEN-LAST:event_botonA13ActionPerformed

    private void botonA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA14ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A14");
    }//GEN-LAST:event_botonA14ActionPerformed

    private void botonA15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA15ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A15");
    }//GEN-LAST:event_botonA15ActionPerformed

    private void botonB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB16ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B16");
    }//GEN-LAST:event_botonB16ActionPerformed

    private void botonB17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB17ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B17");
    }//GEN-LAST:event_botonB17ActionPerformed

    private void botonB18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB18ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B18");
    }//GEN-LAST:event_botonB18ActionPerformed

    private void botonA19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA19ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A19");
    }//GEN-LAST:event_botonA19ActionPerformed

    private void botonA20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA20ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A20");
    }//GEN-LAST:event_botonA20ActionPerformed

    private void botonA21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA21ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A21");
    }//GEN-LAST:event_botonA21ActionPerformed

    private void botonB22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB22ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B22");
    }//GEN-LAST:event_botonB22ActionPerformed

    private void botonB23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB23ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B23");
    }//GEN-LAST:event_botonB23ActionPerformed

    private void botonB24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB24ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B24");
    }//GEN-LAST:event_botonB24ActionPerformed

    private void botonA25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA25ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A25");
    }//GEN-LAST:event_botonA25ActionPerformed

    private void botonA26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA26ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A26");
    }//GEN-LAST:event_botonA26ActionPerformed

    private void botonA27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA27ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A27");
    }//GEN-LAST:event_botonA27ActionPerformed

    private void botonB28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB28ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B28");
    }//GEN-LAST:event_botonB28ActionPerformed

    private void botonB29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB29ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B29");
    }//GEN-LAST:event_botonB29ActionPerformed

    private void botonB30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB30ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B30");
    }//GEN-LAST:event_botonB30ActionPerformed

    private void botonA31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA31ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A31");
    }//GEN-LAST:event_botonA31ActionPerformed

    private void botonA32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA32ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A32");
    }//GEN-LAST:event_botonA32ActionPerformed

    private void botonA33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA33ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A33");
    }//GEN-LAST:event_botonA33ActionPerformed

    private void botonB34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB34ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B34");
    }//GEN-LAST:event_botonB34ActionPerformed

    private void botonB35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB35ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B35");
    }//GEN-LAST:event_botonB35ActionPerformed

    private void botonB36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB36ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B36");
    }//GEN-LAST:event_botonB36ActionPerformed

    private void botonA37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA37ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A37");
    }//GEN-LAST:event_botonA37ActionPerformed

    private void botonA38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA38ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A38");
    }//GEN-LAST:event_botonA38ActionPerformed

    private void botonA39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA39ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A39");
    }//GEN-LAST:event_botonA39ActionPerformed

    private void botonB40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB40ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B40");
    }//GEN-LAST:event_botonB40ActionPerformed

    private void botonB41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB41ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B41");
    }//GEN-LAST:event_botonB41ActionPerformed

    private void botonB42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB42ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B42");
    }//GEN-LAST:event_botonB42ActionPerformed

    private void botonA43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA43ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A43");
    }//GEN-LAST:event_botonA43ActionPerformed

    private void botonA44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA44ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A44");
    }//GEN-LAST:event_botonA44ActionPerformed

    private void botonA45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA45ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("A45");
    }//GEN-LAST:event_botonA45ActionPerformed

    private void botonB46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB46ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B46");
    }//GEN-LAST:event_botonB46ActionPerformed

    private void botonB47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB47ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B47");
    }//GEN-LAST:event_botonB47ActionPerformed

    private void botonB48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB48ActionPerformed
        // TODO add your handling code here:
        campoPuestoSeleccionado.setText("B48");
    }//GEN-LAST:event_botonB48ActionPerformed

    private void botonGenerarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReservaActionPerformed
        // TODO add your handling code here:
        String nombre = campoNombre.getText();
        String apellido = campoApellido.getText();
        String cedula = campoCedula.getText();

        Pasajero pasajero = new Pasajero(nombre, apellido, cedula);
        String tipoPago = comboTipoPago.getSelectedItem().toString();
        String puesto = campoPuestoSeleccionado.getText();
        
        if (nombre.equals("") || apellido.equals("") || cedula.equals("") || puesto.equals("")) {
            JOptionPane.showMessageDialog(null, "No deje los campos vacios");
        }else{
        
            if (puesto.equals("E1") || puesto.equals("E2") || puesto.equals("E3") || puesto.equals("E4")
                || puesto.equals("E5") || puesto.equals("E6") || puesto.equals("E7") || puesto.equals("E8")) {

            Reserva reservaEjecutivo = new ReservaEjecutivo(vueloReserva, pasajero, puesto, tipoPago, vueloReserva.getPrecioClaseEjecutiva());

            if (puesto.equals("E1")) {

                listadoReservasEjecutivo[0][0] = listadoReservas.put(vueloReserva, reservaEjecutivo);
                almacenarReserva();
                JOptionPane.showMessageDialog(null, "Reserva generada");
                botonE1.setEnabled(false);
                salir();

            }

            if (puesto.equals("E2")) {

                listadoReservasEjecutivo[0][1] = listadoReservas.put(vueloReserva, reservaEjecutivo);
                almacenarReserva();
                JOptionPane.showMessageDialog(null, "Reserva generada");
                botonE2.setEnabled(false);
                salir();

            }

        } else {

            Reserva reservaEconomico = new ReservaEconomico(vueloReserva, pasajero, puesto, tipoPago, vueloReserva.getPrecioClaseEconomica());

        }
            
        }

        

    }//GEN-LAST:event_botonGenerarReservaActionPerformed

    public final void cargarReservas(String codigoVuelo) {

        for (Map.Entry<Vuelo, Reserva> entry : listadoReservas.entrySet()) {
            Reserva reserva = entry.getValue();

            if (reserva.getVueloPasajero().getCodigoVuelo().equals(codigoVuelo)) {

                String numeroPuesto = reserva.getNumeroPuesto();

                if (numeroPuesto.equals("E1")) {
                    botonE1.setEnabled(false);
                }
                if (numeroPuesto.equals("E2")) {
                    botonE2.setEnabled(false);
                }
                if (numeroPuesto.equals("E3")) {
                    botonE3.setEnabled(false);
                }
                if (numeroPuesto.equals("E4")) {
                    botonE4.setEnabled(false);
                }
                if (numeroPuesto.equals("E5")) {
                    botonE5.setEnabled(false);
                }
                if (numeroPuesto.equals("E6")) {
                    botonE6.setEnabled(false);
                }
                if (numeroPuesto.equals("E7")) {
                    botonE7.setEnabled(false);
                }
                if (numeroPuesto.equals("E8")) {
                    botonE8.setEnabled(false);
                }

            }

        }

    }

    public final void leerReservas() {
        try {
            FileInputStream fos = new FileInputStream(archivoReservas);
            ObjectInputStream ois = new ObjectInputStream(fos);
            listadoReservas = (HashMap<Vuelo, Reserva>) ois.readObject();
            ois.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Leyendo, aún no existe el archivo: reservas.res");

        }
    }

    public JTextField getCampoCodigoVuelo() {
        return campoCodigoVuelo;
    }

    public void almacenarReserva() {
        FileOutputStream fs;
        ObjectOutputStream os;
        try {

            fs = new FileOutputStream(archivoReservas);
            os = new ObjectOutputStream(fs);

            os.writeObject(listadoReservas);

        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {

        }

    }

    private void salir() {

        int respuesta = JOptionPane.showConfirmDialog(null, "Quiere hacer otra reserva?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (respuesta) {
            case JOptionPane.NO_OPTION:
                dispose();
                break;
            case JOptionPane.YES_OPTION:
                break;
            case JOptionPane.CLOSED_OPTION:
                break;
            default:
                break;
        }
       
    }

    public HashMap<Vuelo, Reserva> getListadoReservas() {
        return listadoReservas;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaVentana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReservaVentana2(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA1;
    private javax.swing.JButton botonA13;
    private javax.swing.JButton botonA14;
    private javax.swing.JButton botonA15;
    private javax.swing.JButton botonA19;
    private javax.swing.JButton botonA2;
    private javax.swing.JButton botonA20;
    private javax.swing.JButton botonA21;
    private javax.swing.JButton botonA25;
    private javax.swing.JButton botonA26;
    private javax.swing.JButton botonA27;
    private javax.swing.JButton botonA3;
    private javax.swing.JButton botonA31;
    private javax.swing.JButton botonA32;
    private javax.swing.JButton botonA33;
    private javax.swing.JButton botonA37;
    private javax.swing.JButton botonA38;
    private javax.swing.JButton botonA39;
    private javax.swing.JButton botonA43;
    private javax.swing.JButton botonA44;
    private javax.swing.JButton botonA45;
    private javax.swing.JButton botonA7;
    private javax.swing.JButton botonA8;
    private javax.swing.JButton botonA9;
    private javax.swing.JButton botonB10;
    private javax.swing.JButton botonB11;
    private javax.swing.JButton botonB12;
    private javax.swing.JButton botonB16;
    private javax.swing.JButton botonB17;
    private javax.swing.JButton botonB18;
    private javax.swing.JButton botonB22;
    private javax.swing.JButton botonB23;
    private javax.swing.JButton botonB24;
    private javax.swing.JButton botonB28;
    private javax.swing.JButton botonB29;
    private javax.swing.JButton botonB30;
    private javax.swing.JButton botonB34;
    private javax.swing.JButton botonB35;
    private javax.swing.JButton botonB36;
    private javax.swing.JButton botonB4;
    private javax.swing.JButton botonB40;
    private javax.swing.JButton botonB41;
    private javax.swing.JButton botonB42;
    private javax.swing.JButton botonB46;
    private javax.swing.JButton botonB47;
    private javax.swing.JButton botonB48;
    private javax.swing.JButton botonB5;
    private javax.swing.JButton botonB6;
    private javax.swing.JButton botonE1;
    private javax.swing.JButton botonE2;
    private javax.swing.JButton botonE3;
    private javax.swing.JButton botonE4;
    private javax.swing.JButton botonE5;
    private javax.swing.JButton botonE6;
    private javax.swing.JButton botonE7;
    private javax.swing.JButton botonE8;
    private javax.swing.JButton botonGenerarReserva;
    private javax.swing.JTextField campoAeropuertoDestino;
    private javax.swing.JTextField campoAeropuertoOrigen;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCodigoVuelo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNombreAerolinea;
    private javax.swing.JTextField campoPrecioEconomico;
    private javax.swing.JTextField campoPrecioEjecutivo;
    private javax.swing.JTextField campoPuestoSeleccionado;
    private javax.swing.JComboBox<String> comboTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelModoPago;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPuestoSeleccionado;
    private javax.swing.JPanel panelImagenAvion;
    // End of variables declaration//GEN-END:variables

}
